### ISSUE TITLE
DarkSouls III: certain geo meshes are converted without textures and vertex colors

### ISSUE THREAD

**Issue by isshininu** [Shadowth117/PSO2-Aqua-Library#10]
First, thank you for making this tool! Super cool thing :)
I'd would like to report a single issue I currently found, some meshes for DS3 are converted without textures and vertex colors, they are all look like this piece of terrain:

![Снимок экрана (1211)](https://github.com/Shadowth117/PSO2-Aqua-Library/assets/6324523/0dd31d4e-8341-4bbc-8045-1868aff765e6)

this is m47_00_00_00_003000 mesh, base terrain for m47 map. M41 terrain (SoC boss arena) also uses same textures for blending (ash_101_a and floor_03_white_a), and both lack vertex colors and material definitions.

**Comment by Shadowth117** [comment]
Commit https://github.com/Shadowth117/PSO2-Aqua-Library/commit/3d7a42e7c360466052a11163bed8ff423f8d46fc resolves the cutoff issue.

**Comment by Shadowth117** [comment]
The current build of Aqua Toolset now has this fix. https://github.com/Shadowth117/Aqua-Toolset/releases
