### ISSUE TITLE
Texture filenames in FromSoft FBX exports have the wrong extension (TGA, but should be DDS)

### ISSUE THREAD

**Issue by Akira13641** [Shadowth117/PSO2-Aqua-Library#5]
I should note this is basically the _only_ flaw I can see in your software as far as FromSoft handling, it is otherwise far superior in that regard to any alternative (since it actually produces correctly rigged FBX files and even copies the aforementioned DDS textures straight out of the compressed DCX archives into the same folder as the exported mesh, and so on).

**Comment by Shadowth117** [comment]
And, added with the latest commit. Good suggestion!

**Comment by Akira13641** [comment]
Thanks a lot!
